# -*- coding: utf-8 -*-
"""shakespear.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cGAR1aLv7BUuOdxwOh63WddI_yrt7gNI

# Shakespeare Sentiment Analysis
"""

!pip install nltk
import string
from nltk.stem import PorterStemmer
import re

"""##Defining Variables"""

stemmer = PorterStemmer()

positive_words = ["love","joy","happy","beautiful","sweet","delight","good","happi"]
negative_words = ["hate","anger","sad","pain","sorrow","fear","bad","angri"]
stopwords = ["the","is","a","and","with","but","not","to","of","in"]
positive_words = [stemmer.stem(word) for word in positive_words]
negative_words = [stemmer.stem(word) for word in negative_words]

def clean_text(text):
    text = text.lower()
    text = text.translate(str.maketrans('', '', string.punctuation))
    return text

def tokenize(text):
    tokens = text.split()
    stemmed_tokens = [stemmer.stem(word) for word in tokens]
    return stemmed_tokens

def remove_stopwords(tokens):
    filtered = []
    for word in tokens:
        if word not in stopwords:
            filtered.append(word)
    return filtered

def analyze_sentiment(tokens):
    score = 0
    negate = False
    for word in tokens:
        if word == "not":
            negate = True
            continue
        if word in positive_words:
            score += -1 if negate else 1
            negate = False
        elif word in negative_words:
            score += 1 if negate else -1
            negate = False
    return score
with open("shakespear.txt", "r") as file:
    text = file.read()

sentences = text.split(".")

for sentence in sentences:

    if sentence.strip() == "":
        continue

    cleaned = clean_text(sentence)
    tokens = tokenize(cleaned)
    filtered = remove_stopwords(tokens)
    score = analyze_sentiment(filtered)

    if score > 0:
        sentiment = "Positive"
    elif score < 0:
        sentiment = "Negative"
    else:
        sentiment = "Neutral"

    print("Sentence:", sentence.strip())
    print("Score:", score)
    print("Sentiment:", sentiment)

